//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXE.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ giao hàng.
        /// </summary>
        public static string AddressShip {
            get {
                return ResourceManager.GetString("AddressShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặt sau.
        /// </summary>
        public static string BackSide {
            get {
                return ResourceManager.GetString("BackSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đen.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi.
        /// </summary>
        public static string ChangeAddress {
            get {
                return ResourceManager.GetString("ChangeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn đầy đủ vật liệu!.
        /// </summary>
        public static string ChooseError {
            get {
                return ResourceManager.GetString("ChooseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn chất liệu.
        /// </summary>
        public static string ChooseItem {
            get {
                return ResourceManager.GetString("ChooseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành phố/Tỉnh thành.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu mới.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tầm nhìn.
        /// </summary>
        public static string Creative {
            get {
                return ResourceManager.GetString("Creative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo ra một cộng đồng sáng tạo có ý nghĩa, nơi mọi người có thể thể hiện bản thân và phát triển tiềm năng của mình thông qua việc sử dụng các sản phẩm sổ tay do chúng tôi tự thiết kế..
        /// </summary>
        public static string Creative_content {
            get {
                return ResourceManager.GetString("Creative_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ ghi nợ.
        /// </summary>
        public static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết kế.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự thiết kế.
        /// </summary>
        public static string DesignByYourSelf {
            get {
                return ResourceManager.GetString("DesignByYourSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận/Huyện.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã có tài khoản chưa?.
        /// </summary>
        public static string Doyou {
            get {
                return ResourceManager.GetString("Doyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        public static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặt trước.
        /// </summary>
        public static string FrontSide {
            get {
                return ResourceManager.GetString("FrontSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chèn.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết kế có sẵn.
        /// </summary>
        public static string ImportDesign {
            get {
                return ResourceManager.GetString("ImportDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai tên tài khoản hoặc mật khẩu.
        /// </summary>
        public static string IncorrectLogin {
            get {
                return ResourceManager.GetString("IncorrectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới không khớp.
        /// </summary>
        public static string IncorrectNewPassword {
            get {
                return ResourceManager.GetString("IncorrectNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai mật khẩu cũ.
        /// </summary>
        public static string IncorrectOldPassword {
            get {
                return ResourceManager.GetString("IncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập địa chỉ!.
        /// </summary>
        public static string InputAddress {
            get {
                return ResourceManager.GetString("InputAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP đã được gửi về email của bạn, hãy check Email!.
        /// </summary>
        public static string MaOTP {
            get {
                return ResourceManager.GetString("MaOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sứ mệnh.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ và truyền cảm hứng cho mọi người trong việc tạo ra sản phẩm sổ tay tự thiết kế độc đáo và mang tính cá nhân..
        /// </summary>
        public static string Material_content {
            get {
                return ResourceManager.GetString("Material_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cuốn sổ.
        /// </summary>
        public static string NameOfNote {
            get {
                return ResourceManager.GetString("NameOfNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú (nếu có).
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng trang.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP.
        /// </summary>
        public static string OTP {
            get {
                return ResourceManager.GetString("OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực mã OTP.
        /// </summary>
        public static string OTPAuthen {
            get {
                return ResourceManager.GetString("OTPAuthen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại giấy.
        /// </summary>
        public static string Paper {
            get {
                return ResourceManager.GetString("Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quét mã QR.
        /// </summary>
        public static string PaymentOn {
            get {
                return ResourceManager.GetString("PaymentOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sản phẩm trong giỏ hàng.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận được sản phẩm như mong muốn!.
        /// </summary>
        public static string Product_content {
            get {
                return ResourceManager.GetString("Product_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cá nhân hóa, sáng tạo, thực tế, bền vững.
        /// </summary>
        public static string Product_home {
            get {
                return ResourceManager.GetString("Product_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trở lại.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đường.
        /// </summary>
        public static string Road {
            get {
                return ResourceManager.GetString("Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn phương thức thanh toán.
        /// </summary>
        public static string SelectAPayment {
            get {
                return ResourceManager.GetString("SelectAPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu còng sổ.
        /// </summary>
        public static string Spring {
            get {
                return ResourceManager.GetString("Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cá nhân.
        /// </summary>
        public static string TTCN {
            get {
                return ResourceManager.GetString("TTCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xã/Phường.
        /// </summary>
        public static string Ward {
            get {
                return ResourceManager.GetString("Ward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coi Demo.
        /// </summary>
        public static string WatchDemo {
            get {
                return ResourceManager.GetString("WatchDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trắng.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có.
        /// </summary>
        public static string Youhave {
            get {
                return ResourceManager.GetString("Youhave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ của bạn đang trống!.
        /// </summary>
        public static string YourAddres {
            get {
                return ResourceManager.GetString("YourAddres", resourceCulture);
            }
        }
    }
}
